/*
@project : https://github.com/wakeupthecat/gastona
@file    : Eva-min.js
@version : 202111

Copyright (C) 2015-2021 Alejandro Xalabarder Aulet

@license : GNU General Public License (GPL) version 3 + commercial license through OpenSoftwareCongoLicenseV0.1

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.
*/
function evaFileObj(c){if(typeof c==="string"){c=evaFileStr2obj(c)}return{obj:c,toText:function(){return d(c)},toString:function(){return d(c)},evaFileObj2Text:d,evaUnitObj2Text:b,evaObj2Text:a};function d(e){var g=[];for(var f in e){if(e.hasOwnProperty(f)){g.push("#"+f+"#");g.push("");g.push(b(e[f]));g.push("")}}return g.join("\n")}function b(e){var g=[];for(var f in e){if(e.hasOwnProperty(f)){g.push("");g.push("   <"+f+">");g.push("");g.push(a(e[f]))}}return g.join("\n")}function a(g){var i=[],f="";for(var h in g){if(g.hasOwnProperty(h)){f="      ";for(var e=0;e<g[h].length;e++){if(e>0){f+=", "}if(e==g[h].length-1){f+="//"}f+=g[h][e]}i.push(f)}}return i.join("\n")}}function evaFile(a){alert("evaFile function name is deprecated! please use evaFileStr2obj instead");evaFileStr2obj(a)}function evaFileUTF82obj(a){return evaFileStr2obj(decodeURIComponent(a.replace(/\+/g,"%20")))}function evaFileStr2obj(h,a,c){function g(i){return i.replace(/^\s+|\s+$/g,"")}function d(i){return i.replace(/\r\n/g,"\r").replace(/\n/g,"\r").split(/\r/)}return e();function f(i,j,l){if(i.charAt(0)!==j){return}var k=i.indexOf(l,1);if(k>0){return{name:i.substr(1,k-1),rest:g(i.substr(k+1))}}}function b(n){var i=[];var l=n.length;var m=0;function o(){return m>=n.length}function j(){var p="";while(m<n.length&&(n.charAt(m)==" "||n.charAt(m)=="\t")){m++}if(o()){return null}if(n.charAt(m)=="'"){p=n.substring(m+1);m=l;return p}if(n.charAt(m)=="/"&&n.charAt(m+1)=="/"){p=n.substring(m+2);m=l;return p}var r=n.charAt(m)=='"';var q=r?++m:m;do{if(r){if(n.charAt(m)!='"'){m++}else{if(n.charAt(m+1)=='"'){p+=(m+1>q?n.substring(q,m+1):"");m+=2;q=m}else{break}}}else{if(n.charAt(m)==","){break}m++}}while(!o());var s=m;if(!r){while(s>q&&(n.charAt(s-1)===" "||n.charAt(s-1)==="\t")){s--}}if(s>q){p+=n.substring(q,s)}m++;if(r){while(!o()&&n.charAt(m)!=","){m++}m++}return p}do{var k=j();if(typeof k==="string"){i.push(k)}}while(!o());return i}function e(){var q,l;var o={},u={},r=[];function m(v){if(l){u[l]=r.length>0?r:[[""]]}l=undefined;r=[];if(v){if(q){o[q]=u}q=undefined;u=[]}}var s=h;if(typeof h==="string"){s=d(h)}var t=+(a||0);var k=+(c||(s.length-1));for(var j=t;j<=k;j++){var i=g(s[j]);if(i.charAt(0)==="<"&&i.charAt(1)==="!"){continue}var n=f(i,"#","#");if(n){if(n.name&&n.name.charAt(0)==="*"&&n.name.charAt(1)=="*"){break}m(true);q=n.name;continue}n=f(i,"<",">");if(n){m(false);l=n.name;i=n.rest;if(i.length==0){continue}}if(i&&q&&l){var p=b(i);if(p){r.push(p)}}else{}}m(true);return o}};